apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnsev6443-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnsev6443-tenant-component
    app.kubernetes.io/part-of: loadnsev6443-tenant-app
  name: loadnsev6443-tenant-component
  namespace: loadnsev6443-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnsev6443-tenant-component
    weight: null
status: {}
