apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnsev6443-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnsev6443-tenant-component
    app.kubernetes.io/part-of: loadnsev6443-tenant-app
  name: loadnsev6443-tenant-component
  namespace: loadnsev6443-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadnsev6443-tenant-component
status:
  loadBalancer: {}
